### ISSUE TITLE
Python code for downloading earning calls from Refinitiv Eikon

### ISSUE THREAD

**Issue by woahidmurad** [hoenie-ams/Eikon-Python#3]
Hi Joris, could you please develop a new code to download (a large amount of) earning call transcripts from Refinitiv Eikon (while I have access to the database) using a python code (like this code you developed)? I appreciate any help you can provide.

**Comment by hoenie-ams** [comment]
Hi @woahidmurad, currently I don't have access to an Eikon terminal, so I can't develop this. Maybe they can help you out at the Refinitiv developer forum?
